"""
Umily — Agent Action Schemas

Pydantic models representing action plans, individual steps, and execution results.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ActionStep(BaseModel):
    """Represents a single executable step within an action plan."""

    step_id: int = Field(..., description="1-indexed step number")
    tool: str = Field(..., description="Tool category e.g. browser, filesystem, windows, desktop")
    action: str = Field(..., description="Action name e.g. navigate, read_file, execute_command")
    resource_type: str = Field(..., description="website, application, filesystem, tool")
    resource_name: str = Field(..., description="Target resource identifier e.g. LeetCode, VS Code, C:/Users")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Key-value arguments for tool call")
    description: str = Field(..., description="Human readable description of the step")
    requires_confirmation: bool = Field(default=False, description="Whether user confirmation is required")
    status: str = Field(default="pending", description="pending, allowed, blocked, waiting_confirmation, executing, completed, failed")
    result: Optional[str] = None
    error: Optional[str] = None


class ActionPlan(BaseModel):
    """Complete plan generated by Gemini or Agent Planner."""

    summary: str = Field(..., description="High-level plan summary")
    intent_type: str = Field(default="COMPUTER_TASK", description="QUESTION, COMPUTER_TASK, COMPUTER_INFO, MIXED_REQUEST")
    answer: Optional[str] = Field(default=None, description="Direct text answer for general knowledge questions")
    steps: List[ActionStep] = Field(default_factory=list, description="List of action steps")


class ActionResult(BaseModel):
    """Result returned after running a plan or individual step."""

    success: bool
    status: str
    message: str
    completed_steps: int
    total_steps: int
    pending_confirmation_step: Optional[ActionStep] = None
    error: Optional[str] = None
